Change student auth
HiruNya/Parsons-Tool pull request #126
Opened 2022-09-23 15:29 UTC by HiruNya

2022-09-23 18:50 UTC, HiruNya commented
Fixes #116

2022-09-24 02:41 UTC, f-fromont commented on parsons-tool-backend/src/routes/api/student.js
> +  // const thisUser = await Users.find({ email: req.currentUser.email });
should thes be commented out?

2022-09-24 02:41 UTC, f-fromont requested changes
Just a question about the commented out code, otherwise it looks good

2022-09-24 06:31 UTC, f-fromont approved these changes

2022-09-24 06:36 UTC, merged

2022-09-24 06:38 UTC, f-fromont commented
issue made for commented code #129